#' Calculate species-level relative abundance from Kraken2 outputs
#'
#' @description
#' This function derives genome-size-aware species-level relative abundance estimates 
#' directly from Kraken2 classification outputs. Standard Kraken2 summaries rely on 
#' read counts or simple assignment proportions, which are heavily biased by varying 
#' reference genome lengths and read-length heterogeneity in nanopore data. 
#' 
#' This function parses the read-level classification strings to aggregate k-mer evidence 
#' assigned specifically to each focal species. It then normalizes this aggregated signal 
#' by the effective reference genome length to yield a coverage-proxy abundance measure. 
#' Finally, these values are scaled within the sample to generate robust relative abundances.
#' 
#' Users can optionally provide a named list of high-quality read IDs generated by 
#' filter_low_info_reads() to restrict the quantification to reliable evidence.
#'
#' @param report_dir Character; directory containing *.report files.
#' @param kraken_dir Character; directory containing *.kraken files.
#' @param k_mer_length Positive integer; k-mer length used by Kraken2. This is 
#'   subtracted from the total genome length to calculate the effective genome 
#'   size (genome_size_bp - k + 1). Default is 35.
#' @param genome_stats_file Character; full path to a tab-delimited genome stats 
#'   file. The first column must contain the TaxID and the second column must 
#'   contain the genome size in base pairs.
#' @param sample_ids Character vector; optional subset of sample IDs (file basenames) 
#'   to process. If NULL, all matched files are processed.
#' @param read_filter Character vector OR named list; an optional whitelist of read IDs 
#'   to retain. If a named list is provided, the function matches IDs to samples by name.
#' @param output_folder Character; directory to write per-sample *.basen result files. 
#'   If NULL, results are written to the current working directory.
#' @param verbose Logical; print progress messages and sanity checks to the console.
#'
#' @return A combined data.table containing the abundance metrics for all processed 
#'   samples. Columns include sample_id, name, taxid, genome_size_bp, bases_assigned, 
#'   reads_assigned, coverage_proxy, and relative_abundance.
#' @export
#'
#' @importFrom dplyr filter mutate rowwise ungroup group_by summarise left_join arrange select n desc
#' @importFrom data.table as.data.table setcolorder fwrite rbindlist
#' 
#' @examples
#' \dontrun{
#' ## Estimate abundance using a read filter from the QC step
#' results <- kraken_relative_abundance(
#'   report_dir = "path/to/reports",
#'   kraken_dir = "path/to/kraken",
#'   genome_stats_file = "path/to/genome_stats.txt",
#'   read_filter = hq_reads,
#'   output_folder = "basen_results"
#' )
#' }
kraken_relative_abundance <- function(report_dir = NULL,
                                      kraken_dir = NULL,
                                      k_mer_length = 35,
                                      genome_stats_file,
                                      sample_ids = NULL,
                                      read_filter = NULL,
                                      output_folder = NULL,
                                      verbose = TRUE) {

        ## Ensure at least one input directory is provided
        if (is.null(report_dir) && is.null(kraken_dir)) {
                stop("At least one of report_dir or kraken_dir must be provided.")
        }
        if (is.null(report_dir)) report_dir <- kraken_dir
        if (is.null(kraken_dir)) kraken_dir <- report_dir

        ## Validate input paths
        if (!dir.exists(report_dir)) stop("Report directory does not exist: ", report_dir)
        if (!dir.exists(kraken_dir)) stop("Kraken directory does not exist: ", kraken_dir)
        if (!file.exists(genome_stats_file)) stop("Genome stats file does not exist: ", genome_stats_file)

        ## Default to current working directory if output_folder is NULL
        if (is.null(output_folder)) {
                output_folder <- getwd()
                if (verbose) message("No output_folder specified. Writing results to: ", output_folder)
        }

        ## Create directory and normalize path to prevent write errors
        if (!dir.exists(output_folder)) {
                dir.create(output_folder, recursive = TRUE)
                if (verbose) message("Created output folder: ", output_folder)
        }
        output_folder <- normalizePath(output_folder)

        ## Identify available samples based on report files
        report_files <- list.files(report_dir, pattern = "\\.report$", full.names = TRUE)
        if (length(report_files) == 0) stop("No report files found in directory.")

        available_ids <- sub("\\.report$", "", basename(report_files))
        sample_ids <- if (!is.null(sample_ids)) intersect(sample_ids, available_ids) else available_ids

        if (verbose) message("Processing ", length(sample_ids), " sample(s).")

        ## Load genome stats and enforce character type for taxid
        genome_stats <- utils::read.table(genome_stats_file, header = FALSE, sep = "\t", stringsAsFactors = FALSE)
        colnames(genome_stats) <- c("taxid", "genome_size_bp")
        genome_stats$taxid <- as.character(genome_stats$taxid)
        
        ## Apply effective genome size adjustment (l - k + 1)
        genome_stats$genome_size_bp <- genome_stats$genome_size_bp - k_mer_length + 1

        result_list <- lapply(sample_ids, function(sample_id) {
                if (verbose) message("Processing sample: ", sample_id)

                report_path <- file.path(report_dir, paste0(sample_id, ".report"))
                kraken_path <- file.path(kraken_dir, paste0(sample_id, ".kraken"))

                if (!file.exists(kraken_path)) {
                        warning("Missing kraken file for ", sample_id, "; skipping.")
                        return(NULL)
                }

                ## Load report and kraken data, enforcing character taxids
                report <- utils::read.table(report_path, sep = "\t", header = FALSE, quote = "", comment.char = "")
                colnames(report) <- c("percent", "reads_clade", "reads_direct", "rank_code", "taxid", "name")
                report$taxid <- as.character(report$taxid)

                kraken <- utils::read.table(kraken_path, sep = "\t", header = FALSE, quote = "", comment.char = "")
                colnames(kraken) <- c("status", "read_id", "taxid", "read_length", "kmer_string")
                kraken$taxid <- as.character(kraken$taxid)

                ## Handle filtration logic for both vector and named list inputs
                if (!is.null(read_filter)) {
                        current_filter <- if (is.list(read_filter)) read_filter[[sample_id]] else read_filter
                        if (!is.null(current_filter)) {
                                kraken <- kraken[kraken$read_id %in% current_filter, ]
                                if (verbose) message(" - Reads after applying quality filter: ", nrow(kraken))
                        }
                }

                ## Extract species-level metadata and classified read evidence
                species_report <- subset(report, rank_code == "S")
                kraken_c <- subset(kraken, status == "C")

                if (nrow(kraken_c) == 0) {
                        warning("No classified reads remain for sample: ", sample_id)
                        return(NULL)
                }

                ## Calculate base-level signal for each species
                species_kmers <- kraken_c |>
                        dplyr::filter(taxid %in% species_report$taxid) |>
                        dplyr::rowwise() |>
                        dplyr::mutate(assigned_kmers = extract_kmer_counts(kmer_string, taxid)) |>
                        dplyr::ungroup()

                ## Final join and normalization with cleaned species names
                base_counts <- species_kmers |>
                        dplyr::group_by(taxid) |>
                        dplyr::summarise(
                                bases_assigned = sum(assigned_kmers), 
                                reads_assigned = dplyr::n(), 
                                .groups = "drop"
                        ) |>
                        dplyr::mutate(taxid = as.character(taxid)) |>
                        dplyr::left_join(species_report[, c("taxid", "name")], by = "taxid") |>
                        dplyr::mutate(name = trimws(name)) |> 
                        dplyr::left_join(genome_stats[, c("taxid", "genome_size_bp")], by = "taxid") |>
                        dplyr::mutate(coverage_proxy = bases_assigned / genome_size_bp)

                ## Calculate relative abundance
                total_coverage <- sum(base_counts$coverage_proxy, na.rm = TRUE)
                base_counts <- base_counts |>
                        dplyr::mutate(
                                relative_abundance = coverage_proxy / total_coverage, 
                                sample_id = sample_id
                        ) |>
                        dplyr::arrange(dplyr::desc(relative_abundance)) |>
                        dplyr::select(sample_id, name, taxid, genome_size_bp, bases_assigned, reads_assigned, coverage_proxy, relative_abundance)

                ## Convert to data.table and save result
                result_dt <- data.table::as.data.table(base_counts)
                out_file <- file.path(output_folder, paste0(sample_id, ".basen"))
                data.table::fwrite(result_dt, out_file, sep = "\t")

                return(result_dt)
        })

        ## Combine all sample results into a single data.table
        combined <- data.table::rbindlist(result_list, use.names = TRUE, fill = TRUE)

        ## Output execution statistics
        message("Execution statistics for kraken_relative_abundance:")
        message("Total samples processed: ", length(sample_ids))
        message("Total files read: ", length(sample_ids) * 2)

        return(combined)
}

#' Extract k-mer counts from Kraken2 assignment strings
#'
#' @description
#' This internal utility function parses the k-mer assignment string generated by 
#' Kraken2 (e.g., "5:10 0:5 5:123" where format is TaxID:Count). It extracts the 
#' numeric counts of k-mers assigned to specific taxa. If a target_taxid is 
#' provided, it rapidly filters and sums only the k-mers assigned to that focal 
#' taxonomic ID. If no target_taxid is provided, it aggregates and returns the 
#' total counts for all unique TaxIDs present in the read.
#'
#' @param kmer_string Character; the k-mer assignment string from a single read 
#'   in the Kraken2 output.
#' @param target_taxid Character; optional specific TaxID. If provided, the function 
#'   only sums k-mers assigned to this exact ID. If NULL, it returns an array of 
#'   counts for all present TaxIDs.
#'
#' @return A numeric value representing the summed k-mer count for the target_taxid, 
#'   or a named numeric vector of counts if no target_taxid is provided.
#' @keywords internal
#' 
#' @examples
#' \dontrun{
#' ## Extract total k-mers assigned to TaxID "123"
#' count <- extract_kmer_counts("0:5 123:10 5:3 123:2", target_taxid = "123")
#' ## count will equal 12
#' }
extract_kmer_counts <- function(kmer_string, 
                                target_taxid = NULL) {

        pairs <- unlist(strsplit(kmer_string, " ", fixed = TRUE))
        taxids <- sub(":.*", "", pairs)
        counts <- as.numeric(sub(".*:", "", pairs))
        result <- NULL

        if (!is.null(target_taxid)) {
                result <- sum(
                        counts[taxids == as.character(target_taxid)],
                        na.rm = TRUE
                )
        } else {
                agg <- tapply(counts, taxids, sum, na.rm = TRUE)
                ord <- order(as.numeric(names(agg)))
                result <- agg[ord]
        }

        return(result)
}