#' Profile read-level k-mer composition from Kraken2 output
#' 
#' @description 
#' This function parses raw Kraken2 output files (*.kraken) to compute read-level 
#' k-mer assignment metrics. For long-read metagenomic data, read length and 
#' assignment ambiguity vary significantly. This function extracts the k-mer string 
#' for each classified read and calculates the total number of k-mers, the number 
#' of k-mers assigned specifically to the primary TaxID, the number of unassigned 
#' k-mers (TaxID 0), and the Shannon diversity index of all taxonomic assignments 
#' within that read. These metrics provide the diagnostic evidence needed to 
#' evaluate assignment quality.
#'
#' @param kraken_file Character; absolute or relative path to a single *.kraken file.
#' @param k_mer_length Positive integer; the k-mer length used during Kraken2 
#'   database construction. Default is 35. This value is used to calculate the 
#'   total possible k-mers for a read of a given length (read_length - k + 1).
#'
#' @return A data.table containing the following read-level metrics:
#'   \itemize{
#'     \item \code{read_id}: Unique identifier for the sequencing read.
#'     \item \code{total_kmers}: Total number of k-mers in the read.
#'     \item \code{assigned_kmers}: Count of k-mers assigned to the read's primary TaxID.
#'     \item \code{unassigned_kmers}: Count of k-mers with no taxonomic assignment (TaxID 0).
#'     \item \code{assigned_perc}: Proportion of assigned k-mers.
#'     \item \code{unassigned_perc}: Proportion of unassigned k-mers.
#'     \item \code{kmers_diversity}: Shannon diversity index of all taxonomic assignments in the read.
#'   }
#' @export
#'
#' @importFrom data.table as.data.table setDT :=
#' 
#' @examples
#' \dontrun{
#' ## Profile a single Kraken2 output file
#' qc_metrics <- profile_kmer_composition(
#'   kraken_file = "sample1.kraken",
#'   k_mer_length = 35
#' )
#' }
profile_kmer_composition <- function(kraken_file,
                                     k_mer_length = 35) {

        if (!file.exists(kraken_file)) {
                stop(paste("Kraken file not found:", kraken_file))
        }

        kraken_df <- utils::read.table(
                kraken_file,
                header = FALSE,
                sep = "\t",
                quote = "",
                stringsAsFactors = FALSE
        )
        colnames(kraken_df) <- c("status", "read_id", "taxid", "read_length", "kmer_string")

        classified_idx <- which(kraken_df$status == "C")
        n_total <- nrow(kraken_df)
        n_classified <- length(classified_idx)

        calc_h <- function(counts) {
                counts <- counts[counts > 0]
                if (length(counts) == 0) return(0)
                p <- counts / sum(counts)
                return(-sum(p * log(p)))
        }

        res_list <- lapply(classified_idx, function(i) {
                k_str <- kraken_df$kmer_string[i]
                tid   <- kraken_df$taxid[i]
                rlen  <- kraken_df$read_length[i]

                all_counts <- extract_kmer_counts(k_str)
                assigned   <- extract_kmer_counts(k_str, target_taxid = tid)
                unassigned <- extract_kmer_counts(k_str, target_taxid = "0")

                total_k <- rlen - k_mer_length + 1

                data.frame(
                        read_id = kraken_df$read_id[i],
                        total_kmers = total_k,
                        assigned_kmers = assigned,
                        unassigned_kmers = unassigned,
                        kmers_diversity = calc_h(all_counts),
                        stringsAsFactors = FALSE
                )
        })

        kmer_profile <- data.table::as.data.table(do.call(rbind, res_list))
        kmer_profile[, assigned_perc := assigned_kmers / total_kmers]
        kmer_profile[, unassigned_perc := unassigned_kmers / total_kmers]

        message("Execution statistics for profile_kmer_composition:")
        message("Number of files read: 1")
        message("Total reads processed: ", n_total)
        message("Classified reads profiled: ", n_classified)

        return(kmer_profile)
}

#' Filter reads based on k-mer composition metrics
#'
#' @description
#' This function takes the read-level metrics generated by profile_kmer_composition 
#' and applies user-defined thresholds to filter out ambiguous or low-information reads. 
#' To support efficient multi-sample workflows, it returns a named list of whitelisted 
#' read IDs organized by sample_id.
#'
#' @param kmer_profile A data.table output generated by profile_kmer_composition. 
#'   Must include a 'sample_id' column for multi-sample filtering.
#' @param max_unassigned_perc Numeric; the maximum allowable proportion of unassigned 
#'   k-mers in a single read. Reads above this threshold are excluded. Default is 0.5.
#' @param max_shannon_diversity Numeric; the maximum allowable Shannon diversity 
#'   index for a read's taxonomic assignments. Reads above this threshold are excluded. 
#'   Default is 1.0.
#'
#' @return A named list of character vectors. Names correspond to sample_id, and 
#'   values are the read_id values that passed the filters.
#' @export
#' 
#' @examples
#' \dontrun{
#' ## Extract high-quality reads by sample
#' hq_reads_list <- filter_low_info_reads(
#'   kmer_profile = combined_qc,
#'   max_unassigned_perc = 0.5,
#'   max_shannon_diversity = 1.0
#' )
#' }
filter_low_info_reads <- function(kmer_profile,
                                  max_unassigned_perc = 0.5,
                                  max_shannon_diversity = 1.0) {

        # Apply the AND condition filter
        filtered_dt <- kmer_profile[
                unassigned_perc <= max_unassigned_perc &
                kmers_diversity <= max_shannon_diversity
        ]

        if ("sample_id" %in% colnames(kmer_profile)) {
                passed_reads <- split(filtered_dt$read_id, filtered_dt$sample_id)
                num_samples <- length(unique(kmer_profile$sample_id))
        } else {
                passed_reads <- filtered_dt$read_id
                num_samples <- 1
        }

        message("Execution statistics for filter_low_info_reads:")
        message("Number of samples processed: ", num_samples)
        message("Total reads evaluated: ", nrow(kmer_profile))
        message("Total reads passing filter: ", 
                if(is.list(passed_reads)) sum(lengths(passed_reads)) else length(passed_reads))

        return(passed_reads)
}

#' Plot read-level k-mer quality control diagnostics
#'
#' @description
#' This function generates a density-based diagnostic visualization to evaluate 
#' the quality of Kraken2 taxonomic assignments at the single-read level. It 
#' maps the proportion of unassigned k-mers against the Shannon diversity of 
#' assigned k-mers (`kmers_diversity`) using a 2D binning approach.
#' 
#' High-quality, high-confidence reads typically cluster in the lower-left 
#' quadrant (low unassigned proportion and low diversity, indicating a dominant 
#' species signal). Conversely, reads in the upper-right quadrant represent 
#' low-information evidence—likely arising from low-complexity regions, 
#' horizontal gene transfer, or poor-quality sequencing—and should be filtered 
#' before abundance estimation.
#'
#' @param kmer_profile A data.table generated by profile_kmer_composition. 
#'   Must contain 'unassigned_perc' and 'kmers_diversity' columns.
#'
#' @return A ggplot2 object representing a 2D density plot of read-level metrics.
#' @export
#' 
#' @examples
#' \dontrun{
#' ## Visualize the quality distribution of a sample
#' qc_plot <- plot_kmer_qc(qc_metrics)
#' print(qc_plot)
#' }
plot_kmer_qc <- function(kmer_profile) {
        
        # Gemini 3.1 Flash
        if (is.null(kmer_profile) || nrow(kmer_profile) == 0) {
                stop("kmer_profile is empty. Cannot generate plot.")
        }

        # Ensure ggplot2 is available
        if (!requireNamespace("ggplot2", quietly = TRUE)) {
                stop("Package 'ggplot2' is required for this function.")
        }

        # Build the plot using verified column names
        # x = Proportion of unassigned k-mers
        # y = Shannon index of assigned k-mers
        p <- ggplot2::ggplot(kmer_profile, 
                             ggplot2::aes(x = unassigned_perc, y = kmers_diversity)) +
                ggplot2::geom_bin2d(bins = 100) +
                ggplot2::scale_fill_viridis_c(option = "magma", trans = "log10") +
                ggplot2::theme_minimal() +
                ggplot2::labs(
                        title = "Read-level k-mer assignment quality",
                        x = "Proportion of unassigned k-mers",
                        y = "Shannon diversity (kmers_diversity)",
                        fill = "Log10(Count)"
                ) +
                ggplot2::theme(
                        plot.title = ggplot2::element_text(face = "bold"),
                        panel.grid.minor = ggplot2::element_blank(),
                        legend.position = "bottom" 
                )

        # Execution statistics as per user standards
        message("Execution statistics for plot_kmer_qc:")
        message("Number of data frames processed: 1")
        message("Total reads visualized: ", nrow(kmer_profile))
        message("Number of plots generated: 1")
        
        return(p)
}
