#' Collect basen per-sample metrics from output files
#'
#' @description
#' This function reads multiple per-sample *.basen result files (generated by 
#' kraken_relative_abundance) and consolidates the requested metrics into a single 
#' long-format data.table. Users can choose to extract relative abundance, the 
#' coverage proxy, or both. To maintain a clean and standardized matrix for downstream 
#' statistical tools, genome metadata columns (such as species name and genome_size_bp) 
#' are intentionally excluded from the aggregated output.
#'
#' @param output_folder Character; directory containing the per-sample result files.
#' @param files Character vector; optional explicit list of full paths to result files. 
#'   If provided, the output_folder parameter is ignored.
#' @param pattern Character; regular expression file name pattern used to identify 
#'   result files within the output folder. Default is "\\.basen$".
#' @param metric Character; specifies which metric(s) to collect from the files. 
#'   Options are "relative_abundance", "coverage_proxy", or "both".
#' @param verbose Logical; print progress messages and sanity checks to the console.
#'
#' @return A long-format data.table containing the columns: sample_id, taxid, and 
#'   the requested metric(s).
#' @export
#'
#' @importFrom data.table fread rbindlist as.data.table
#' @importFrom tools file_path_sans_ext
#' 
#' @examples
#' \dontrun{
#' ## Collect the coverage proxy metrics across all samples in a directory
#' metric_table <- collect_basen_metrics(
#'   output_folder = "basen_results",
#'   metric = "coverage_proxy"
#' )
#' }
collect_basen_metrics <- function(output_folder = NULL,
                                  files = NULL,
                                  pattern = "\\.basen$",
                                  metric = c("relative_abundance", "coverage_proxy", "both"),
                                  verbose = TRUE) {

        metric <- match.arg(metric)

        if (is.null(output_folder) && is.null(files)) {
                stop("Either output_folder or files must be provided.")
        }

        if (!is.null(files)) {
                missing <- files[!file.exists(files)]
                if (length(missing) > 0) stop("The following files do not exist: ", paste(missing, collapse = ", "))
                result_files <- files
        } else {
                if (!dir.exists(output_folder)) stop("Results directory does not exist: ", output_folder)
                result_files <- list.files(output_folder, pattern = pattern, full.names = TRUE)
                if (length(result_files) == 0) stop("No result files found in directory.")
        }

        metric_cols <- switch(
                metric,
                relative_abundance = "relative_abundance",
                coverage_proxy     = "coverage_proxy",
                both               = c("relative_abundance", "coverage_proxy")
        )
        required_cols <- c("taxid", metric_cols)

        res <- lapply(result_files, function(f) {
                dt <- data.table::fread(f, sep = "\t")

                missing_cols <- setdiff(required_cols, colnames(dt))
                if (length(missing_cols) > 0) stop("File ", basename(f), " is missing required columns: ", paste(missing_cols, collapse = ", "))

                sample_id <- tools::file_path_sans_ext(basename(f))
                out <- dt[, ..required_cols]
                out[, sample_id := sample_id]
                out <- out[, c("sample_id", required_cols), with = FALSE]
                return(out)
        })

        combined <- data.table::rbindlist(res, use.names = TRUE)

        message("Execution statistics for collect_basen_metrics:")
        message("Total files read: ", length(result_files))
        message("Total samples processed: ", length(unique(combined$sample_id)))
        message("Total rows aggregated: ", nrow(combined))

        return(data.table::as.data.table(combined))
}

#' Calculate size factors from a coverage proxy matrix
#'
#' @description
#' This function calculates per-sample size factors for cross-sample normalization, 
#' akin to the approaches used in transcriptomics (e.g., DESeq2). It expects a 
#' matrix of coverage proxy values (not relative abundances) to retain the total-depth 
#' information required for scaling. It builds a pseudo-reference sample by calculating 
#' the geometric mean of coverage for each taxon across all samples, calculates the 
#' per-sample ratios compared to this reference, and derives a size factor using 
#' either the median or geometric mean of these ratios. Taxa with zero counts across 
#' samples are excluded from the reference calculation.
#'
#' @param x A numeric matrix (or data.frame coercible to a matrix) where rows are 
#'   taxids and columns are sample IDs. Cell values must represent coverage proxies.
#' @param method Character; the summarization method for the ratios, either "median" 
#'   or "geomean". Default is "median".
#' @param verbose Logical; print progress messages and sanity checks to the console.
#'
#' @return A named numeric vector of computed size factors for each sample.
#' @export
#'
#' @importFrom stats median setNames
#' 
#' @examples
#' \dontrun{
#' ## Assuming coverage_matrix is a taxid-by-sample matrix
#' size_factors <- calc_size_factors(
#'   x = coverage_matrix,
#'   method = "median"
#' )
#' 
#' ## Normalize the original matrix by the computed size factors
#' normalized_matrix <- sweep(coverage_matrix, 2, size_factors, FUN = "/")
#' }
calc_size_factors <- function(x,
                              method = c("median", "geomean"),
                              verbose = TRUE) {

        method <- match.arg(method)

        if (is.data.frame(x)) x <- as.matrix(x)
        if (!is.matrix(x)) stop("Input x must be a matrix.")

        if (!is.numeric(x)) suppressWarnings(storage.mode(x) <- "numeric")
        if (!is.numeric(x)) stop("Input x must be numeric.")

        if (nrow(x) < 2 || ncol(x) < 2) stop("Matrix must have at least 2 rows and 2 columns.")
        if (is.null(rownames(x)) || anyNA(rownames(x)) || any(rownames(x) == "")) stop("Matrix must have valid rownames representing taxids.")
        if (is.null(colnames(x)) || anyNA(colnames(x)) || any(colnames(x) == "")) stop("Matrix must have valid colnames representing sample ids.")
        if (any(!is.finite(x), na.rm = TRUE)) stop("Matrix contains non-finite values.")

        taxa_ok <- apply(x, 1, function(v) all(v > 0))
        if (sum(taxa_ok) == 0) stop("No taxa have strictly positive coverage proxy across all samples.")
        
        x_use <- x[taxa_ok, , drop = FALSE]

        ref <- exp(rowMeans(log(x_use)))
        ratios <- sweep(x_use, 1, ref, FUN = "/")

        if (method == "median") {
                sf <- apply(ratios, 2, function(v) stats::median(v, na.rm = TRUE))
        } else {
                sf <- apply(ratios, 2, function(v) exp(mean(log(v), na.rm = TRUE)))
        }

        if (any(!is.finite(sf)) || any(sf <= 0)) stop("Computed invalid size factors.")

        sf <- stats::setNames(as.numeric(sf), colnames(x_use))

        message("Execution statistics for calc_size_factors:")
        message("Total matrices processed: 1")
        message("Taxa used for reference: ", nrow(x_use))
        message("Size factors calculated: ", length(sf))

        return(sf)
}